global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: cv-site

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: vm-host

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mtail'
    static_configs:
      - targets: ['mtail:3903']

  - job_name: 'promtail'
    static_configs:
      - targets: ['localhost:9080'] # Or your Promtail container name/IP
  - job_name: 'authelia'
    scrape_interval: 15s
    scheme: http
    static_configs:
      - targets: ['authelia:9959']   # container name resolves inside internal network
    relabel_configs:
      - target_label: instance
        replacement: 'authelia'
